### ISSUE TITLE
Document how to register vector type in doctrine

### ISSUE THREAD

**Issue by tacman** [inspector-apm/neuron-ai#131]
```php
    #[ORM\Column(type: VectorType::VECTOR, length: 3072)]
    public ?array $embedding = null;
```

But type 'vector' isn't recognized.

In UnknownColumnType.php line 15:
                                                                                                                                                                                            
  Unknown column type "vector" requested. Any Doctrine type that you use has to be registered with \Doctrine\DBAL\Types\Type::addType(). You can get a list of all the known types with \D  
  octrine\DBAL\Types\Type::getTypesMap(). If this error occurs during database introspection then you might have forgotten to register all database types for a Doctrine Type. Use Abstrac  
  tPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMappedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot s  
  ome mapping information.                                                                                                                                                                  
                                                                                                                                                                                            

I think there's a way to do it in doctrine.yaml, but I forget how.  If you have it in a project somewhere, can you add that to the documentation?

**Comment by tacman** [comment]
It appears that sqlite isn't supported, only mysql and postgresql, so that should probably be mentioned in the docs.

I read somewhere that pinecone uses sqlite, but I'm not sure.  I image that sqlite could be supported too.

**Comment by tacman** [comment]
Getting there.

AbstractPlatform no longer has getName()

https://github.com/doctrine/dbal/issues/4749

```yaml
doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            vector: NeuronAI\RAG\VectorStore\Doctrine\VectorType
```

Not even sure that's right.

**Comment by ilvalerione** [comment]
@AlexandreCavanna can you help here?

**Comment by AlexandreCavanna** [comment]
This snippet is correct — you’re right, we should include it in the documentation. I had forgotten this part of the configuration. We should also add the NeuronAI namespace to the mappings section to ensure it works properly with the `#[ORM\MappedSuperclass]` attribute defined in DoctrineEmbeddingEntityBase.php. This tells Doctrine to scan that part of the schema, even though it’s located outside of the default `src/Entity` directory from a Symfony project for example.

This is the configuration I’m using:

```yaml
doctrine:
    dbal:
        types:
            vector: NeuronAI\RAG\VectorStore\Doctrine\VectorType
    orm:
        mappings:
            NeuronAI:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/vendor/inspector-apm/neuron-ai/src/RAG/VectorStore/Doctrine'
                prefix: 'NeuronAI\RAG\VectorStore\Doctrine'
```

The vector type was introduced in MariaDB 11.7, so you must be using at least this version. For PostgreSQL, it is available through the [pgvector](https://github.com/pgvector/pgvector) extension, which needs to be enabled. We should make sure to mention this.

**Comment by tacman** [comment]
Are you using the latest version of doctrine?  Can you do a `composer outdated` and confirm?

**Comment by AlexandreCavanna** [comment]
`doctrine/orm 2.10.0   3.3.3   Object-Relational-Mapper for PHP`

**Comment by AlexandreCavanna** [comment]
We’re not on the latest major version yet, we’re still on a Symfony 5.4 project, where we’re working through legacy dependencies and other deprecations.

**Comment by tacman** [comment]
The config doesn't work.  mappings is under orm:, not dbal.

Symfony is at version 7.3.  5.4 is on life support.  This project is cutting edge!  Why are you limiting yourself to outdated tools?  Given how new the project is, you don't have legacy customers to support, so why not prioritize the latest release versions of everything: PHP 8.4, Symfony 7.3, doctrine dbal 4, etc.

PLEASE publish your working example code, I can help upgrade them (or report bugs when I can't).  It's really, really hard to take the snippets and turn them into working code.

**Comment by AlexandreCavanna** [comment]
I edited my reply.

**Comment by AlexandreCavanna** [comment]
> Symfony is at version 7.3. 5.4 is on life support. This project is cutting edge! Why are you limiting yourself to outdated tools? Given how new the project is, you don't have legacy customers to support, so why not prioritize the latest release versions of everything: PHP 8.4, Symfony 7.3, doctrine dbal 4, etc.

Sorry, I think I wasn't clear enough when I wasn't talking about neuron ai but about another project where neuron ai is used as you know, when you have to take over a project with a lot of legacy, things don't happen with a snap of the fingers to fix deprecations, update dependencies and so on... In an ideal world, we’d all like to be up to date.

Nevertheless THANK YOU FOR YOU SUGGESTION  cpt obvious ;)

Here a working example code with Symfony 5.4,  doctrine/orm 2.10:

```php
<?php

namespace NeuronAI\RAG\VectorStore\Doctrine;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use NeuronAI\RAG\Document;

#[ORM\MappedSuperclass]
class DoctrineEmbeddingEntityBase extends Document
{
    #[ORM\Id]
    #[ORM\Column(name: 'id', type: 'integer')]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    public mixed $id;

    #[ORM\Column(type: VectorType::VECTOR, length: 3072)]
    public ?array $embedding = null;

    #[ORM\Column(type: Types::TEXT)]
    public string $content;

    #[ORM\Column(type: Types::TEXT)]
    public string $sourceType = 'manual';

    #[ORM\Column(type: Types::TEXT)]
    public string $sourceName = 'manual';

    #[ORM\Column(type: Types::INTEGER)]
    public int $chunkNumber = 0;

    public function getId(): ?string
    {
        return $this->id;
    }
}
```

```php
<?php

namespace Capco\AppBundle\Entity\Vector;

use Capco\AppBundle\Repository\ResponseVectorRepository;
use Doctrine\ORM\Mapping as ORM;
use NeuronAI\RAG\VectorStore\Doctrine\DoctrineEmbeddingEntityBase;

#[ORM\Entity(repositoryClass: ResponseVectorRepository::class)]
#[ORM\Table(name: 'response_vector')]
class ResponseVector extends DoctrineEmbeddingEntityBase
{
    #[ORM\Id]
    #[ORM\Column(type: 'guid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'UUID')]
    public mixed $id;
}
```

```yaml
doctrine:
    dbal:
        types:
            vector: NeuronAI\RAG\VectorStore\Doctrine\VectorType
    orm:
        mappings:
            NeuronAI:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/vendor/inspector-apm/neuron-ai/src/RAG/VectorStore/Doctrine'
                prefix: 'NeuronAI\RAG\VectorStore\Doctrine'
```

We should improved documentation for sure that's a point, for the rest feel free to test and contribute with latest versions of Symfony/Doctrine if you need to confirm some behavior.
